<?php
/**
 * Add submenu page for CSV import under Book Reviews
 */
function rswpbs_add_review_import_submenu() {
    add_submenu_page(
        'edit.php?post_type=book_reviews', // Parent slug
        'Import Reviews From Amazon',  // Page title
        'Import Reviews From Amazon',   // Menu title
        'manage_options',               // Capability
        'rswpbs-import-reviews',        // Menu slug
        'rswpbs_render_import_reviews_page' // Callback
    );
}
add_action('admin_menu', 'rswpbs_add_review_import_submenu');

/**
 * Render the import reviews page
 */
function rswpbs_render_import_reviews_page() {
    ?>
    <div class="wrap">
        <h1><?php esc_html_e('Import Book Reviews from CSV', 'rswpbs'); ?></h1>
        <?php
        // Handle form submission
        if (isset($_POST['rswpbs_import_reviews_nonce']) && wp_verify_nonce($_POST['rswpbs_import_reviews_nonce'], 'rswpbs_import_reviews')) {
            rswpbs_process_reviews_csv_import();
        }
        ?>
        <form method="post" enctype="multipart/form-data">
            <?php wp_nonce_field('rswpbs_import_reviews', 'rswpbs_import_reviews_nonce'); ?>
            <table class="form-table">
                <tr>
                    <th><label for="reviewed_book"><?php esc_html_e('Select Book', 'rswpbs'); ?></label></th>
                    <td>
                        <select name="reviewed_book" id="reviewed_book" required>
                            <option value=""><?php esc_html_e('Select a Book', 'rswpbs'); ?></option>
                            <?php
                            $book_query = new WP_Query([
                                'post_type' => 'book',
                                'posts_per_page' => -1,
                            ]);
                            while ($book_query->have_posts()) {
                                $book_query->the_post();
                                $book_id = get_the_ID();
                                ?>
                                <option value="<?php echo esc_attr($book_id); ?>">
                                    <?php echo esc_html(get_the_title()); ?>
                                </option>
                                <?php
                            }
                            wp_reset_postdata();
                            ?>
                        </select>
                        <p class="description"><?php esc_html_e('Select the book these reviews are for.', 'rswpbs'); ?></p>
                    </td>
                </tr>
                <tr>
                    <th><label for="csv_file"><?php esc_html_e('Upload CSV File', 'rswpbs'); ?></label></th>
                    <td>
                        <input type="file" name="csv_file" id="csv_file" accept=".csv" required>
                        <p class="description"><?php esc_html_e('Upload the CSV file generated by the Amazon review scraper.', 'rswpbs'); ?></p>
                    </td>
                </tr>
            </table>
            <?php submit_button('Import Reviews'); ?>
        </form>
    </div>
    <?php
}

/**
 * Process the CSV import
 */
function rswpbs_process_reviews_csv_import() {
    if (!isset($_FILES['csv_file']) || $_FILES['csv_file']['error'] !== UPLOAD_ERR_OK) {
        ?>
        <div class="notice notice-error is-dismissible">
            <p><?php esc_html_e('Error: Please upload a valid CSV file.', 'rswpbs'); ?></p>
        </div>
        <?php
        return;
    }

    if (!isset($_POST['reviewed_book']) || empty($_POST['reviewed_book'])) {
        ?>
        <div class="notice notice-error is-dismissible">
            <p><?php esc_html_e('Error: Please select a book.', 'rswpbs'); ?></p>
        </div>
        <?php
        return;
    }

    $reviewed_book = intval($_POST['reviewed_book']);
    $file = $_FILES['csv_file']['tmp_name'];

    // Read CSV file
    if (($handle = fopen($file, 'r')) !== false) {
        $header = fgetcsv($handle); // Read header row
        $expected_headers = ['Reviewer Name', 'Review Title', 'Review Rating', 'Review Content', 'Review Media'];

        // Validate headers
        if ($header !== $expected_headers) {
            ?>
            <div class="notice notice-error is-dismissible">
                <p><?php esc_html_e('Error: CSV file does not have the expected headers.', 'rswpbs'); ?></p>
            </div>
            <?php
            fclose($handle);
            return;
        }

        $imported = 0;
        $errors = [];

        while (($row = fgetcsv($handle)) !== false) {
            $reviewer_name = sanitize_text_field($row[0]);
            $review_title = sanitize_text_field($row[1]);
            $review_rating = intval($row[2]);
            $review_content = sanitize_textarea_field($row[3]);

            // Wrap line breaks with <p> tags
            $paragraphs = array_filter(array_map('trim', explode("\n", $review_content)));
            $formatted_content = '';
            foreach ($paragraphs as $paragraph) {
                if (!empty($paragraph)) {
                    $formatted_content .= '<p>' . $paragraph . '</p>';
                }
            }

            // $review_media = $row[4]; // Not used

            // Validate data
            if (empty($reviewer_name) || empty($review_content) || $review_rating < 1 || $review_rating > 5) {
                $errors[] = sprintf(
                    __('Invalid data for review by %s: Name, content, or rating (1–5) is invalid.', 'rswpbs'),
                    $reviewer_name ?: 'Unknown'
                );
                continue;
            }

            // Create new book_reviews post
            $post_id = wp_insert_post([
                'post_title' => $review_title,
                'post_content' => $formatted_content,
                'post_type' => 'book_reviews',
                'post_status' => 'publish',
                'post_author' => get_current_user_id(),
            ], true);

            if (is_wp_error($post_id)) {
                $errors[] = sprintf(
                    __('Failed to import review by %s: %s', 'rswpbs'),
                    $reviewer_name,
                    $post_id->get_error_message()
                );
                continue;
            }

            // Save meta fields
            update_post_meta($post_id, '_rswpbs_reviewer_name', $reviewer_name);
            update_post_meta($post_id, '_rswpbs_reviewer_email', ''); // No email in CSV, set empty
            update_post_meta($post_id, '_rswpbs_rating', $review_rating);
            update_post_meta($post_id, '_rswpbs_reviewed_book', $reviewed_book);

            $imported++;
        }

        fclose($handle);

        // Display results
        if ($imported > 0) {
            ?>
            <div class="notice notice-success is-dismissible">
                <p><?php printf(esc_html__('Successfully imported %d reviews.', 'rswpbs'), $imported); ?></p>
            </div>
            <?php
        }
        if (!empty($errors)) {
            ?>
            <div class="notice notice-error is-dismissible">
                <p><?php esc_html_e('Some reviews could not be imported:', 'rswpbs'); ?></p>
                <ul>
                    <?php foreach ($errors as $error) : ?>
                        <li><?php echo esc_html($error); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php
        }
    } else {
        ?>
        <div class="notice notice-error is-dismissible">
            <p><?php esc_html_e('Error: Could not read the CSV file.', 'rswpbs'); ?></p>
        </div>
        <?php
    }
}